### ISSUE TITLE
Several tests fail locally (Ubuntu)

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/complement-crypto#13]
The following tests fail when I run the suite on my Ubuntu 20.04 machine:

* TestFailedKeysClaimRetries
* TestRoomKeyIsCycledOnDeviceLogout
* TestRoomKeyIsCycledOnMemberLeaving
* TestSigkillBeforeKeysUploadResponse

Launch script:

```
#!/bin/bash

set -u
set -o pipefail

export LIBRARY_PATH="$(pwd)/rust-sdk/target/debug"
export LD_LIBRARY_PATH="$(pwd)/rust-sdk/target/debug"

export COMPLEMENT_BASE_IMAGE=homeserver
export COMPLEMENT_ENABLE_DIRTY_RUNS=1
export COMPLEMENT_CRYPTO_WRITE_CONTAINER_LOGS=1
export COMPLEMENT_SHARE_ENV_PREFIX=PASS_
export PASS_SYNAPSE_COMPLEMENT_DATABASE=sqlite
export DOCKER_BUILDKIT=1
export BUILDAH_FORMAT=docker

set -x

LOGFILE="~/Desktop/test-output-$(date '+%Y-%m-%d_%H:%M:%S').jsonl"

go test -v -timeout 15m -json ./tests "$@" 2>&1 \
    | tee "${LOGFILE} \
    | gotestfmt -hide successful-tests
```

Logs: [complement-crypto-failures.txt](https://github.com/matrix-org/complement-crypto/files/14451214/complement-crypto-failures.txt)

**Comment by kegsay** [comment]
All of those tests use a callback server. Likely networking problem to the host.
