### ISSUE TITLE
Test: If you get a lot of to-device msgs all at once, ensure they are processed in-order

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/complement-crypto#35]
See https://github.com/element-hq/element-web/issues/25723

**Comment by kegsay** [comment]
This is tougher to do, as we really want the test itself to be a client so it can interleave misordered room keys around. It would require us to either use libolm (which is a hard dep on Complement today) or vodozemac. It feels wrong to be using vodozemac to test vodozemac though...

**Comment by kegsay** [comment]
One alternative would be to:
 - block `/sync`
 - Spin up a lot of clients (e.g 50) which will join the same room and send 5 msgs (causing to-device msgs to be sent), especially with a low rotation period (1 msg), this will cause 5x50=250 to-device msgs
 - unblock `/sync`
 - the next `/sync` will have hundreds of to-device msgs
 - ensure all messages can be decrypted.
